config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :kandydats
      resources :kandydat_wybories
      resources :typ_wyborows
      resources :wyborcas
      resources :wyborca_wybories
      resources :wybories
      resources :partias

      root to: "kandydats#index"
  end

  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'
  get 'partias/index'
  get 'partias/show'
  get 'partias/new'
  post 'partias/create'
  get 'partias/edit'
  patch 'partias/update'
  delete 'partias/destroy'
  get 'wyborca_wybories/index'
  get 'wyborca_wybories/show'
  get 'wyborca_wybories/new'
  post 'wyborca_wybories/create'
  get 'wyborca_wybories/edit'
  patch 'wyborca_wybories/update'
  delete 'wyborca_wybories/destroy'
  get 'kandydat_wybories/index'
  get 'kandydat_wybories/show'
  get 'kandydat_wybories/new'
  post 'kandydat_wybories/create'
  get 'kandydat_wybories/edit'
  patch 'kandydat_wybories/update'
  delete 'kandydat_wybories/destroy'
  get 'kandydats/index'
  get 'kandydats/show'
  get 'kandydats/new'
  post 'kandydats/create'
  get 'kandydats/edit'
  patch 'kandydats/update'
  delete 'kandydats/destroy'
  get 'typ_wyborows/index'
  get 'typ_wyborows/show'
  get 'typ_wyborows/new'
  post 'typ_wyborows/create'
  get 'typ_wyborows/edit'
  patch 'typ_wyborows/update'
  delete 'typ_wyborows/destroy'
  get 'wybories/index'
  get 'wybories/show'
  get 'wybories/new'
  post 'wybories/create'
  get 'wybories/edit'
  patch 'wybories/update'
  delete 'wybories/destroy'
  get 'wyborcas/index'
  get 'wyborcas/show'
  get 'wyborcas/new'
  post 'wyborcas/create'
  get 'wyborcas/edit'
  patch 'wyborcas/update'
  delete 'wyborcas/destroy'
  
  resources :wyborcas
  resources :typ_wyborows
  resources :wybories do
    collection do
      get 'wyniki'
    end
  end
  resources :kandydats do
    post 'glosuj', on: :member
    get 'dziekuje', on: :member
  end
  resources :kandydat_wybories
  resources :wyborca_wybories
  resources :partias
  
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'

  root 'public#home'
end

app/models/wybory.rb
class Wybory < ApplicationRecord
  belongs_to :typ_wyborow, class_name: 'TypWyborow', foreign_key: 'id_typu_wyborow'
  has_many :kandydat_wybories, dependent: :destroy
  has_many :kandydats, through: :kandydat_wybories

  validates :tytul, presence: true
  validates :data_rozpoczecia, presence: true
  validates :data_zakonczenia, presence: true
  validates :max_votes, numericality: { only_integer: true, greater_than: 0 }

  scope :active, -> { where(zakonczone: false) }
  scope :completed, -> { where(zakonczone: true) }

  def self.mark_as_completed
    where("data_zakonczenia < ?", Time.current).update_all(zakonczone: true)
  end

  def aktywne?
    data_rozpoczecia <= Time.current && data_zakonczenia >= Time.current
  end

  def czas_do_zakonczenia
    czas_pozostaly = data_zakonczenia - Time.current
    if czas_pozostaly > 0
      "#{(czas_pozostaly / 1.day).to_i} dni, #{((czas_pozostaly % 1.day) / 1.hour).to_i} godzin, #{(((czas_pozostaly % 1.day) % 1.hour) / 1.minute).to_i} minut"
    else
      "Zakończone"
    end
  end
end

  

app/controllers/admin/wybories_controller.rb
module Admin
  class WyboriesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/wybories_controller.rb
class WyboriesController < ApplicationController
  def index
    @wybories = Wybory.where("data_zakonczenia >= ?", Time.current)
  end

  def show
    @wybory = Wybory.find(params[:id])
    if @wybory.data_zakonczenia < Time.current
      redirect_to root_path, alert: 'Te wybory już się zakończyły.'
    else
      @kandydaci = @wybory.kandydats
    end
  end

  def new
    @wybory = Wybory.new
  end

  def create
    @wybory = Wybory.new(wybory_params)
    if @wybory.save
      redirect_to @wybory, notice: 'Wybory zostały pomyślnie utworzone.'
    else
      render :new
    end
  end

  def edit
    @wybory = Wybory.find(params[:id])
  end

  def update
    @wybory = Wybory.find(params[:id])
    if @wybory.update(wybory_params)
      redirect_to @wybory
    else
      render :edit
    end
  end

  def destroy
    @wybory = Wybory.find(params[:id])
    @wybory.destroy
    redirect_to wybories_path
  end

  def wyniki
    @zakonczone_wybory = Wybory.where('data_zakonczenia < ?', Time.current).order(data_zakonczenia: :desc)
  end

  private

  def wybory_params
    params.require(:wybory).permit(:tytul, :id_typu_wyborow, :data_rozpoczecia, :data_zakonczenia, :kryteria_glosowania, :max_votes)
  end
end

app/helpers/wybories_helper.rb
module WyboriesHelper
end

app/views/wybories/create.html.erb
<h1>Wybories#create</h1>
<p>Find me in app/views/wybories/create.html.erb</p>

app/views/wybories/destroy.html.erb
<h1>Wybories#destroy</h1>
<p>Find me in app/views/wybories/destroy.html.erb</p>

app/views/wybories/edit.html.erb
<h1>Wybories#edit</h1>
<p>Find me in app/views/wybories/edit.html.erb</p>

app/views/wybories/index.html.erb
<h1>Lista wyborów</h1>

<% if @wybories.any? %>
  <% @wybories.each do |wybory| %>
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title"><%= wybory.tytul %></h5>
        <p class="card-text">Data rozpoczęcia: <%= wybory.data_rozpoczecia %></p>
        <p class="card-text">Data zakończenia: <%= wybory.data_zakonczenia %></p>
        <%= link_to 'Zobacz szczegóły', wybory_path(wybory), class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
<% else %>
  <p>Brak aktywnych wyborów.</p>
<% end %>

app/views/wybories/new.html.erb
<h1>Nowe Wybory</h1>

<%= form_with(model: wybory, local: true) do |form| %>
  <% if wybory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wybory.errors.count, "error") %> prohibited this wybory from being saved:</h2>

      <ul>
        <% wybory.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tytul %>
    <%= form.text_field :tytul %>
  </div>

  <div class="field">
    <%= form.label :id_typu_wyborow %>
    <%= form.number_field :id_typu_wyborow %>
  </div>

  <div class="field">
    <%= form.label :data_rozpoczecia %>
    <%= form.datetime_select :data_rozpoczecia %>
  </div>

  <div class="field">
    <%= form.label :data_zakonczenia %>
    <%= form.datetime_select :data_zakonczenia %>
  </div>

  <div class="field">
    <%= form.label :kryteria_glosowania %>
    <%= form.text_area :kryteria_glosowania %>
  </div>

  <div class="field">
    <%= form.label :max_votes %>
    <%= form.number_field :max_votes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= link_to 'Wróć', wybories_path %>

app/views/wybories/show.html.erb
<h1><%= @wybory.tytul %></h1>

<h2>Kandydaci</h2>
<% if @kandydaci.any? %>
  <% @kandydaci.each do |kandydat| %>
    <div class="card mb-3">
      <div class="card-body">
        <h5 class="card-title"><%= kandydat.imie %> <%= kandydat.nazwisko %></h5>
        <p class="card-text">Rok urodzenia: <%= kandydat.rok_urodzenia %></p>
        <p class="card-text">Partia: <%= kandydat.partia.try(:nazwa) %></p>
        <p class="card-text">Liczba głosów: <%= kandydat.ilosc_glosow %></p>
        <%= button_to 'Oddaj głos', glosuj_kandydat_path(kandydat, wybory_id: @wybory.id), method: :post, class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
<% else %>
  <p>Brak kandydatów w tych wyborach.</p>
<% end %>

app/views/wybories/update.html.erb
<h1>Wybories#update</h1>
<p>Find me in app/views/wybories/update.html.erb</p>

app/views/wybories/wyniki.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wyniki Wyborów</title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5/5hb7O91p1QdNpC0XTy5EV6lgrBjuGB4fbu71/0" crossorigin="anonymous">
</head>
<body>
  <div class="container mt-4">
    <h1 class="mb-4">Wyniki Zakończonych Wyborów</h1>
    <% @zakonczone_wybory.each do |wybory| %>
      <div class="card mb-4">
        <div class="card-header">
          <h2><%= wybory.tytul %></h2>
          <p>Data zakończenia: <%= wybory.data_zakonczenia.strftime('%d-%m-%Y') %></p>
        </div>
        <div class="card-body">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Imię</th>
                <th>Nazwisko</th>
                <th>Ilość Głosów</th>
              </tr>
            </thead>
            <tbody>
              <% wybory.kandydats.order(ilosc_glosow: :desc).each do |kandydat| %>
                <tr>
                  <td><%= kandydat.imie %></td>
                  <td><%= kandydat.nazwisko %></td>
                  <td><%= kandydat.ilosc_glosow %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>
  </div>

  <!-- Bootstrap JS and dependencies -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa5s3be2ee1ihb5C5wtgllFDr" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+r+MXC5pRQ1D1Vaz5T2eGiNX6tGmDz3Xr1Nx2DuR3mP9zdB" crossorigin="anonymous"></script>
</body>
</html>