config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :kandydats
      resources :kandydat_wybories
      resources :typ_wyborows
      resources :wyborcas
      resources :wyborca_wybories
      resources :wybories
      resources :partias

      root to: "kandydats#index"
  end

  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'
  get 'partias/index'
  get 'partias/show'
  get 'partias/new'
  post 'partias/create'
  get 'partias/edit'
  patch 'partias/update'
  delete 'partias/destroy'
  get 'wyborca_wybories/index'
  get 'wyborca_wybories/show'
  get 'wyborca_wybories/new'
  post 'wyborca_wybories/create'
  get 'wyborca_wybories/edit'
  patch 'wyborca_wybories/update'
  delete 'wyborca_wybories/destroy'
  get 'kandydat_wybories/index'
  get 'kandydat_wybories/show'
  get 'kandydat_wybories/new'
  post 'kandydat_wybories/create'
  get 'kandydat_wybories/edit'
  patch 'kandydat_wybories/update'
  delete 'kandydat_wybories/destroy'
  get 'kandydats/index'
  get 'kandydats/show'
  get 'kandydats/new'
  post 'kandydats/create'
  get 'kandydats/edit'
  patch 'kandydats/update'
  delete 'kandydats/destroy'
  get 'typ_wyborows/index'
  get 'typ_wyborows/show'
  get 'typ_wyborows/new'
  post 'typ_wyborows/create'
  get 'typ_wyborows/edit'
  patch 'typ_wyborows/update'
  delete 'typ_wyborows/destroy'
  get 'wybories/index'
  get 'wybories/show'
  get 'wybories/new'
  post 'wybories/create'
  get 'wybories/edit'
  patch 'wybories/update'
  delete 'wybories/destroy'
  get 'wyborcas/index'
  get 'wyborcas/show'
  get 'wyborcas/new'
  post 'wyborcas/create'
  get 'wyborcas/edit'
  patch 'wyborcas/update'
  delete 'wyborcas/destroy'
  
  resources :wyborcas
  resources :typ_wyborows
  resources :wybories do
    collection do
      get 'wyniki'
    end
  end
  resources :kandydats do
    post 'glosuj', on: :member
    get 'dziekuje', on: :member
  end
  resources :kandydat_wybories
  resources :wyborca_wybories
  resources :partias
  
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'

  root 'public#home'
end

app/models/partia.rb
class Partia < ApplicationRecord
    self.table_name = "partias"
    has_many :kandydats
  end
  

app/controllers/admin/partias_controller.rb
module Admin
  class PartiasController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/partias_controller.rb
class PartiasController < ApplicationController
  # Wyświetla wszystkie partie.
  #
  # @return [void]
  def index
    @partias = Partia.all
    Rails.logger.info "Wyświetlono listę partii."
  end

  # Wyświetla szczegóły konkretnej partii.
  #
  # @return [void]
  def show
    @partia = Partia.find(params[:id])
    Rails.logger.info "Wyświetlono szczegóły partii o ID: #{@partia.id}."
  end

  # Inicjuje nowy obiekt partii.
  #
  # @return [void]
  def new
    @partia = Partia.new
    Rails.logger.info "Inicjowano nowy obiekt partii."
  end

  # Tworzy nową partię na podstawie podanych parametrów.
  #
  # @return [void]
  def create
    @partia = Partia.new(partia_params)
    if @partia.save
      Rails.logger.info "Utworzono nową partię o ID: #{@partia.id}."
      redirect_to @partia
    else
      Rails.logger.warn "Nie udało się utworzyć nowej partii. Błędy: #{@partia.errors.full_messages.join(', ')}"
      render :new
    end
  end

  # Edytuje istniejącą partię.
  #
  # @return [void]
  def edit
    @partia = Partia.find(params[:id])
    Rails.logger.info "Edytowano partię o ID: #{@partia.id}."
  end

  # Aktualizuje istniejącą partię na podstawie podanych parametrów.
  #
  # @return [void]
  def update
    @partia = Partia.find(params[:id])
    if @partia.update(partia_params)
      Rails.logger.info "Zaktualizowano partię o ID: #{@partia.id}."
      redirect_to @partia
    else
      Rails.logger.warn "Nie udało się zaktualizować partii o ID: #{@partia.id}. Błędy: #{@partia.errors.full_messages.join(', ')}"
      render :edit
    end
  end

  # Usuwa istniejącą partię.
  #
  # @return [void]
  def destroy
    @partia = Partia.find(params[:id])
    @partia.destroy
    Rails.logger.info "Usunięto partię o ID: #{@partia.id}."
    redirect_to partias_path
  end

  private

  # Definiuje dozwolone parametry dla partii.
  #
  # @return [ActionController::Parameters] Zwraca dozwolone parametry.
  def partia_params
    params.require(:partia).permit(:nazwa)
  end
end

app/helpers/partias_helper.rb
module PartiasHelper
end

app/views/partias/create.html.erb
<h1>Partias#create</h1>
<p>Find me in app/views/partias/create.html.erb</p>

app/views/partias/destroy.html.erb
<h1>Partias#destroy</h1>
<p>Find me in app/views/partias/destroy.html.erb</p>

app/views/partias/edit.html.erb
<h1>Partias#edit</h1>
<p>Find me in app/views/partias/edit.html.erb</p>

app/views/partias/index.html.erb
<!-- app/views/partie/index.html.erb -->
<h1>Lista Partii</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Nazwa</th>
     
    </tr>
  </thead>
  <tbody>
    <% @partias.each do |partia| %>
      <tr>
        <td><%= partia.id %></td>
        <td><%= partia.nazwa %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Dodaj nową partię', new_partia_path %>

app/views/partias/new.html.erb
<!-- app/views/kandydats/new.html.erb -->
<h1>Dodaj nowego kandydata</h1>

<%= form_with(model: @partia, url: partias_path) do |form| %>
  <% if @partia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kandydat.errors.count, "błąd") %> nie pozwoliło zapisać kandydata:</h2>
      <ul>
        <% @pasrtia.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= form.label :nazwa %>
    <%= form.text_field :nazwa %>
  </div>

  <div class="actions">
    <%= form.submit 'Dodaj Partie' %>
  </div>
<% end %>

<%= link_to 'Wróć do listy', kandydats_path %>

app/views/partias/show.html.erb
<h1>Partias#show</h1>
<p>Find me in app/views/partias/show.html.erb</p>

app/views/partias/update.html.erb
<h1>Partias#update</h1>
<p>Find me in app/views/partias/update.html.erb</p>