config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :kandydats
      resources :kandydat_wybories
      resources :typ_wyborows
      resources :wyborcas
      resources :wyborca_wybories
      resources :wybories
      resources :partias

      root to: "kandydats#index"
  end

  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'
  get 'partias/index'
  get 'partias/show'
  get 'partias/new'
  post 'partias/create'
  get 'partias/edit'
  patch 'partias/update'
  delete 'partias/destroy'
  get 'wyborca_wybories/index'
  get 'wyborca_wybories/show'
  get 'wyborca_wybories/new'
  post 'wyborca_wybories/create'
  get 'wyborca_wybories/edit'
  patch 'wyborca_wybories/update'
  delete 'wyborca_wybories/destroy'
  get 'kandydat_wybories/index'
  get 'kandydat_wybories/show'
  get 'kandydat_wybories/new'
  post 'kandydat_wybories/create'
  get 'kandydat_wybories/edit'
  patch 'kandydat_wybories/update'
  delete 'kandydat_wybories/destroy'
  get 'kandydats/index'
  get 'kandydats/show'
  get 'kandydats/new'
  post 'kandydats/create'
  get 'kandydats/edit'
  patch 'kandydats/update'
  delete 'kandydats/destroy'
  get 'typ_wyborows/index'
  get 'typ_wyborows/show'
  get 'typ_wyborows/new'
  post 'typ_wyborows/create'
  get 'typ_wyborows/edit'
  patch 'typ_wyborows/update'
  delete 'typ_wyborows/destroy'
  get 'wybories/index'
  get 'wybories/show'
  get 'wybories/new'
  post 'wybories/create'
  get 'wybories/edit'
  patch 'wybories/update'
  delete 'wybories/destroy'
  get 'wyborcas/index'
  get 'wyborcas/show'
  get 'wyborcas/new'
  post 'wyborcas/create'
  get 'wyborcas/edit'
  patch 'wyborcas/update'
  delete 'wyborcas/destroy'
  
  resources :wyborcas
  resources :typ_wyborows
  resources :wybories do
    collection do
      get 'wyniki'
    end
  end
  resources :kandydats do
    post 'glosuj', on: :member
    get 'dziekuje', on: :member
  end
  resources :kandydat_wybories
  resources :wyborca_wybories
  resources :partias
  
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'

  root 'public#home'
end

app/models/wyborca.rb
class Wyborca < ApplicationRecord
  has_secure_password

  validates :imie, presence: true
  validates :nazwisko, presence: true
  validates :numer_tel, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, confirmation: true
  validates :password_confirmation, presence: true
  end
  

app/controllers/admin/wyborcas_controller.rb
module Admin
  class WyborcasController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/wyborcas_controller.rb
class WyborcasController < ApplicationController
  # Wyświetla listę wszystkich wyborców.
  #
  # @return [void]
  def index
    @wyborcy = Wyborca.all
    Rails.logger.info "Wyświetlono listę wszystkich wyborców."
  end

  # Wyświetla szczegóły konkretnego wyborcy.
  #
  # @return [void]
  def show
    @wyborca = Wyborca.find(params[:id])
    Rails.logger.info "Wyświetlono szczegóły wyborcy o ID: #{@wyborca.id}."
  end

  # Inicjuje nowy obiekt wyborcy.
  #
  # @return [void]
  def new
    @wyborca = Wyborca.new
    Rails.logger.info "Inicjowano nowy obiekt wyborcy."
  end

  # Tworzy nowego wyborcę na podstawie podanych parametrów.
  #
  # @return [void]
  def create
    @wyborca = Wyborca.new(wyborca_params)
    if @wyborca.save
      # UserMailer.registration_confirmation(@wyborca).deliver_now
      Rails.logger.info "Utworzono nowego wyborcę o ID: #{@wyborca.id}."
      redirect_to root_path, notice: 'Konto zostało założone pomyślnie.'
    else
      Rails.logger.warn "Nie udało się utworzyć nowego wyborcy. Błędy: #{@wyborca.errors.full_messages.join(', ')}"
      render :new
    end
  end

  # Edytuje istniejącego wyborcę.
  #
  # @return [void]
  def edit
    @wyborca = Wyborca.find(params[:id])
    Rails.logger.info "Edytowano wyborcę o ID: #{@wyborca.id}."
  end

  # Aktualizuje istniejącego wyborcę na podstawie podanych parametrów.
  #
  # @return [void]
  def update
    @wyborca = Wyborca.find(params[:id])
    if @wyborca.update(wyborca_params)
      Rails.logger.info "Zaktualizowano wyborcę o ID: #{@wyborca.id}."
      redirect_to @wyborca
    else
      Rails.logger.warn "Nie udało się zaktualizować wyborcy o ID: #{@wyborca.id}. Błędy: #{@wyborca.errors.full_messages.join(', ')}"
      render :edit
    end
  end

  # Usuwa istniejącego wyborcę.
  #
  # @return [void]
  def destroy
    @wyborca = Wyborca.find(params[:id])
    @wyborca.destroy
    Rails.logger.info "Usunięto wyborcę o ID: #{@wyborca.id}."
    redirect_to wyborcas_path
  end

  private

  # Definiuje dozwolone parametry dla wyborcy.
  #
  # @return [ActionController::Parameters] Zwraca dozwolone parametry.
  def wyborca_params
    params.require(:wyborca).permit(:imie, :nazwisko, :numer_tel, :email, :password, :password_confirmation)
  end
end

app/helpers/wyborcas_helper.rb
module WyborcasHelper
end

app/views/wyborcas/create.html.erb
<h1>Wyborcas#create</h1>
<p>Find me in app/views/wyborcas/create.html.erb</p>

app/views/wyborcas/destroy.html.erb
<h1>Wyborcas#destroy</h1>
<p>Find me in app/views/wyborcas/destroy.html.erb</p>

app/views/wyborcas/edit.html.erb
<h1>Wyborcas#edit</h1>
<p>Find me in app/views/wyborcas/edit.html.erb</p>

app/views/wyborcas/index.html.erb
<h1>Lista Wyborców</h1>
<table>
  <thead>
    <tr>
      <th>Imię</th>
      <th>Nazwisko</th>
      <th>Numer Telefonu</th>
      <th>Email</th>
      <th>Akcje</th>
    </tr>
  </thead>
  <tbody>
    <% @wyborcy.each do |wyborca| %>
      <tr>
        <td><%= wyborca.imie %></td>
        <td><%= wyborca.nazwisko %></td>
        <td><%= wyborca.numer_tel %></td>
        <td><%= wyborca.email %></td>
        <td>
          <%= link_to 'Pokaż', wyborca %>
          <%= link_to 'Edytuj', edit_wyborca_path(wyborca) %>
          <%= link_to 'Usuń', wyborca, method: :delete, data: { confirm: 'Czy na pewno?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Dodaj nowego wyborcę', new_wyborca_path %>

app/views/wyborcas/new.html.erb
<h1>Załóż darmowe konto</h1>
<%= form_with(model: @wyborca, url: wyborcas_path, local: true) do |form| %>
  <% if @wyborca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wyborca.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
        <% @wyborca.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :imie %>
    <%= form.text_field :imie, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :nazwisko %>
    <%= form.text_field :nazwisko, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :numer_tel %>
    <%= form.text_field :numer_tel, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Zarejestruj się', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/wyborcas/show.html.erb
<h1>Wyborcas#show</h1>
<p>Find me in app/views/wyborcas/show.html.erb</p>

app/views/wyborcas/update.html.erb
<h1>Wyborcas#update</h1>
<p>Find me in app/views/wyborcas/update.html.erb</p>