config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :kandydats
      resources :kandydat_wybories
      resources :typ_wyborows
      resources :wyborcas
      resources :wyborca_wybories
      resources :wybories
      resources :partias

      root to: "kandydats#index"
  end

  get 'sessions/new'
  post 'sessions/create'
  delete 'sessions/destroy'
  get 'partias/index'
  get 'partias/show'
  get 'partias/new'
  post 'partias/create'
  get 'partias/edit'
  patch 'partias/update'
  delete 'partias/destroy'
  get 'wyborca_wybories/index'
  get 'wyborca_wybories/show'
  get 'wyborca_wybories/new'
  post 'wyborca_wybories/create'
  get 'wyborca_wybories/edit'
  patch 'wyborca_wybories/update'
  delete 'wyborca_wybories/destroy'
  get 'kandydat_wybories/index'
  get 'kandydat_wybories/show'
  get 'kandydat_wybories/new'
  post 'kandydat_wybories/create'
  get 'kandydat_wybories/edit'
  patch 'kandydat_wybories/update'
  delete 'kandydat_wybories/destroy'
  get 'kandydats/index'
  get 'kandydats/show'
  get 'kandydats/new'
  post 'kandydats/create'
  get 'kandydats/edit'
  patch 'kandydats/update'
  delete 'kandydats/destroy'
  get 'typ_wyborows/index'
  get 'typ_wyborows/show'
  get 'typ_wyborows/new'
  post 'typ_wyborows/create'
  get 'typ_wyborows/edit'
  patch 'typ_wyborows/update'
  delete 'typ_wyborows/destroy'
  get 'wybories/index'
  get 'wybories/show'
  get 'wybories/new'
  post 'wybories/create'
  get 'wybories/edit'
  patch 'wybories/update'
  delete 'wybories/destroy'
  get 'wyborcas/index'
  get 'wyborcas/show'
  get 'wyborcas/new'
  post 'wyborcas/create'
  get 'wyborcas/edit'
  patch 'wyborcas/update'
  delete 'wyborcas/destroy'
  
  resources :wyborcas
  resources :typ_wyborows
  resources :wybories do
    collection do
      get 'wyniki'
    end
  end
  resources :kandydats do
    post 'glosuj', on: :member
    get 'dziekuje', on: :member
  end
  resources :kandydat_wybories
  resources :wyborca_wybories
  resources :partias
  
  get '/logout', to: 'sessions#destroy', as: 'logout'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'

  root 'public#home'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WyboryOnline</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+Knujsl5/5hb7O91p1QdNpC0XTy5EV6lgrBjuGB4fbu71/0" crossorigin="anonymous">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light">
      <a class="navbar-brand" href="/">WyboryOnline</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="<%= wyniki_wybories_path %>">Wyniki</a>
          </li>
          <% if logged_in? %>
            <li class="nav-item">
              <a class="nav-link" href="<%= wybories_path %>">Lista Wyborów</a>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', logout_path, method: :get, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="<%= login_path %>">Login</a>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <!-- Alert messages -->
    <div class="container mt-4">
      <% if notice %>
        <div class="alert alert-info">
          <%= notice %>
        </div>
      <% end %>

      <% if alert %>
        <div class="alert alert-danger">
          <%= alert %>
        </div>
      <% end %>

      <%= yield %>
    </div>

    <footer class="footer text-center text-lg-start mt-4">
      <div class="text-center p-3">
        © 2023 WyboryOnline:
        <a class="text-light" href="https://yourwebsite.com/">yourwebsite.com</a>
      </div>
    </footer>

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa5s3be2ee1ihb5C5wtgllFDr" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+r+MXC5pRQ1D1Vaz5T2eGiNX6tGmDz3Xr1Nx2DuR3mP9zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>